site_name: Pets Off Road

nav:
- Início: index.md
- Projeto: projeto.md
- Visão: doc_visao.md
- Tecnologia: tecnologias.md
- Comunicação: doc_Comunicacao.md

theme: 
  name: material

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde