site_name: Pets Off Road

nav:
- Início: index.md
- Visão: doc_visao.md
- Comunicação: doc_Comunicacao.md
- Apresentações: apresentacoes.md
- Políticas do Repositório: 
    - Como contribuir: contributing.md

theme: 
  name: material

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde