site_name: Pets Off Road

nav:
- Início: index.md
- Projeto: projeto.md
- Produto: produto.md
- Tecnologia: tecnologias.md

theme: 
  name: material

markdown_extensions:
  - pymdownx.tasklist
  - pymdownx.emoji
  - pymdownx.mark
  - pymdownx.tilde