site_name: Pets Off Road

nav:
        - Início: index.md
        - Site Desenvolvido: http://159.223.189.251:5173/
        - Visão: doc_visao.md
        - Comunicação: doc_Comunicacao.md
        - Apresentações:
                  - Unidade 1: apresentacoes/unidade_01.md
                  - Unidade 2: apresentacoes/unidade_02.md
                  - Unidade 4: apresentacoes/unidade_04.md
        - Políticas do Repositório:
                  - Como contribuir: contributing.md
        - Workshop: workshop.md
        - Requisitos: requisitos.md
        - Canvas MVP: canvas.md
        - MVP: MVPs.md
        - Kanban: kanban.md
        - SAFe - Backlog: backlog.md
        - PBB: PBB.md
        - User Story Mapping: map.md
        - Teste:
                  - Estratégia de Testes: testes.md
                  - Casos de Teste: casos_de_testes.md
        - Arquitetura:
                  - Produto: produto/arquitetura/Arquitetura.md
        - Reporte: Reporte.md
        - Protótipo: interface.md
        - Casos de Uso:
                  - Diagrama de Casos de Uso: diagramaCasosdeUso.md
                  - Especificação de Casos de Uso: especificacoes.md
        - Sprints:
                  # - Sprint 1:
                  # - Sprint 2:
                  # - Sprint 3:
                  # - Sprint 4:
                  # - Sprint 5:
                  - Sprint 6:
                            - Planning: sprints/sprint6/planning/planning.md
                            - Review: sprints/sprint6/review/review.md
                            - Restrospective: sprints/sprint6/retrospective/retrospective.md
                  - Sprint 7:
                            - Planning: sprints/sprint7/planning/planning.md
                            - Review: sprints/sprint7/review/review.md
                            - Retrospective: sprints/sprint7/retrospective/retrospective.md
                  - Sprint 8:
                            - Planning: sprints/sprint8/planning/planning.md
                            - Review: sprints/sprint8/review/review.md
                            - Retrospective: sprints/sprint8/retrospective/retrospective.md
                  - Sprint 9:
                            - Planning: sprints/sprint9/planning/planning.md
                            - Review: sprints/sprint9/review/review.md
                            - Retrospective: sprints/sprint9/retrospective/retrospective.md
                  - Sprint 10:
                            - Planning: sprints/sprint10/planning/planning.md
                            - Review: sprints/sprint10/review/review.md
                            - Retrospetive: sprints/sprint10/retrospective/retrospective.md
                  - Sprint 11:
                            - Planning: sprints/sprint11/planning/planning.md
                            - Review: sprints/sprint11/review/review.md
                            - Retrospective: sprints/sprint11/retrospective/retrospective.md
                  - Sprint 12:
                            - Planning: sprints/sprint12/planning/planning.md
                            - Review: sprints/sprint12/review/review.md
                            - Retrospective: sprints/sprint12/retrospective/retrospective.md
                  - Sprint 13:
                            - Planning: sprints/sprint13/planning/planning.md
                            - Review: sprints/sprint13/review/review.md
                            - Retrospective: sprints/sprint13/retrospective/retrospective.md
theme:
        name: material

markdown_extensions:
        - pymdownx.tasklist
        - pymdownx.emoji
        - pymdownx.mark
        - pymdownx.tilde
